name: core
description: A new Flutter module.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#
# This version is used _only_ for the Runner app, which is used if you just do
# a `flutter run` or a `flutter make-host-app-editable`. It has no impact
# on any other native host app that you embed your Flutter project into.
version: 1.0.0+1

environment:
  sdk: ">=2.3.0-dev <3.0.0"

dependencies:
  meta: ^1.1.6
  equatable: ^0.2.0
  bloc: ^0.9.0
  mobx: 0.3.5
  built_value: ^6.3.2
  http: ^0.12.0+1
  tuple: 1.0.2
  intl: 0.16.0
  # app auth for authenticate
  flutter_appauth:
    path: ../../flutter_appauth

dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  build_runner: ^1.6.2
  built_value_generator: ^6.3.2
  mobx_codegen: 0.3.3+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true
  module:
    androidPackage: com.bittrex.core
    iosBundleIdentifier: com.bittrex.core
